package com.example.jbdl.demosecurity;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

@SpringBootApplication
public class DemoSecurityApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoSecurityApplication.class, args);

		BCryptPasswordEncoder bCryptPasswordEncoder = new BCryptPasswordEncoder(10);
		String s1 = bCryptPasswordEncoder.encode("sagar123");
		String s2 = bCryptPasswordEncoder.encode("priyank123");

		System.out.println(s1 + " " + s2);


		BCryptPasswordEncoder encoder2 = new BCryptPasswordEncoder(25);

		System.out.println(encoder2.matches("sagar123", s1));
	}

//	DF94942A31EE452A88ABB06DCBE2E98E

//	DF94942A31EE452A88ABB06DCBE2E98E // Unauthenticated user


//	87F98B5A1F6E111A65B6B198E099C999 // Authenticated user Response header in /login API
//	87F98B5A1F6E111A65B6B198E099C999 // Sent as a cookie in Request header by FE in /hello API
}

// Application Context - IOC
// Security context - sessions


// 29a69378-bf96-4611-95e7-f6afaea788c9 - Pwd generated by Spring
// 8e51a240-5240-43a5-af80-487ec7b98d1f
// X(21402C3E7114FA1FF886FE564DBECFB9) != Y (1761D6AFC347C5C2BBBA63AAAA983D25)