package com.example.demojpa;

import lombok.*;

import javax.persistence.*;
import java.io.Serializable;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity // Used to tell hibernate to map this object to a table in database
public class User implements Serializable {

    // create table user (id int primary key auto_increment)

    /**
        * IDENTITY - The auto incremented values are generated by mysql
        * AUTO - The auto incremented values ae generated by hibernate

        * Person, User, Transaction - 1, 2, 3 - AUTO
        * Person, User, Transaction - 1, 1, 1 - IDENTITY
     **/

    // Author and User are AUTO and transaction is IDENTITY
    /*
        1. Author - 1
        2. User - 2
        3. transaction - 1
        4. transaction - 2
        5. user - 3
        6. author - 4
     */

    @Id // Primary key
    @GeneratedValue(strategy = GenerationType.AUTO) // Hibernate's auto increment
    private int id;

    private String firstName;

    private String lastName;
    private int age;

    @Column(name = "senior_citizen")
    private boolean isSeniorCitizen;

    @Column(unique = true, nullable = false, length = 30)
    private String email;
}
